import { Asset } from '../models';

export const MOCK_ASSETS: Asset[] = [
  // --- IMAGES (5) ---
  {
    id: 'ast-001',
    name: 'hero-background',
    assetType: 'image',
    size: 2451200,
    dateAdded: new Date('2026-01-15T08:30:00Z'),
    tags: ['marketing', 'homepage', 'vibrant'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/hero-bg.jpg',
    previewUrl: 'https://assets.example.com/previews/hero-bg.jpg',
  },
  {
    id: 'ast-002',
    name: 'company-logo-vector',
    assetType: 'image',
    size: 45200,
    dateAdded: new Date('2026-01-20T14:15:00Z'),
    tags: ['branding', 'logo', 'vector'],
    previewUrl: 'https://assets.example.com/previews/logo.svg',
  },
  {
    id: 'ast-003',
    name: 'product-shot-01',
    assetType: 'image',
    size: 5120000,
    dateAdded: new Date('2026-02-02T11:00:00Z'),
    tags: ['e-commerce', 'product', 'isolated'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/prod-01.jpg',
    previewUrl: 'https://assets.example.com/previews/prod-01.png',
  },
  {
    id: 'ast-004',
    name: 'loading-spinner-active',
    assetType: 'image',
    size: 320000,
    dateAdded: new Date('2026-02-18T16:45:00Z'),
    tags: ['ui', 'animation', 'loader'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/spinner.jpg',
  },
  {
    id: 'ast-005',
    name: 'blog-thumbnail-optimized',
    assetType: 'image',
    size: 185000,
    dateAdded: new Date('2026-03-01T09:15:00Z'),
    tags: ['blog', 'content', 'compressed'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/blog-thumb.jpg',
  },

  // --- VIDEOS (4) ---
  {
    id: 'ast-006',
    name: 'product-explainer-final',
    assetType: 'video',
    size: 48200000,
    dateAdded: new Date('2026-03-10T10:00:00Z'),
    tags: ['marketing', 'video', 'tutorial'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/explainer.jpg',
    previewUrl: 'https://assets.example.com/previews/explainer-stream.m3u8',
  },
  {
    id: 'ast-007',
    name: 'raw-interview-footage',
    assetType: 'video',
    size: 1240000000,
    dateAdded: new Date('2026-03-22T17:30:00Z'),
    tags: ['raw', 'interview', 'internal'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/interview.jpg',
  },
  {
    id: 'ast-008',
    name: 'hero-background-loop',
    assetType: 'video',
    size: 8400000,
    dateAdded: new Date('2026-04-05T13:20:00Z'),
    tags: ['ui', 'video', 'loop'],
    previewUrl: 'https://assets.example.com/previews/bg-loop.webm',
  },
  {
    id: 'ast-009',
    name: 'legacy-archive-ad',
    assetType: 'video',
    size: 315000000,
    dateAdded: new Date('2026-04-12T11:05:00Z'),
    tags: ['archive', 'advertisement', 'legacy'],
  },

  // --- DOCUMENTS (6) ---
  {
    id: 'ast-010',
    name: 'brand-guidelines-2026',
    assetType: 'pdf',
    size: 15400000,
    dateAdded: new Date('2026-04-15T09:00:00Z'),
    tags: ['branding', 'legal', 'guidelines'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/guidelines.jpg',
    previewUrl: 'https://assets.example.com/previews/guidelines.pdf',
  },
  {
    id: 'ast-011',
    name: 'employment-contract-template',
    assetType: 'word',
    size: 245000,
    dateAdded: new Date('2026-04-20T15:40:00Z'),
    tags: ['hr', 'legal', 'template'],
  },
  {
    id: 'ast-012',
    name: 'q1-financial-report',
    assetType: 'excel',
    size: 1250000,
    dateAdded: new Date('2026-05-02T10:15:00Z'),
    tags: ['finance', 'q1', 'report'],
  },
  {
    id: 'ast-013',
    name: 'investor-pitch-deck',
    assetType: 'powerPoint',
    size: 32400000,
    dateAdded: new Date('2026-05-10T14:00:00Z'),
    tags: ['funding', 'pitch', 'presentation'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/pitch-deck.jpg',
  },
  {
    id: 'ast-014',
    name: 'user-feedback-export',
    assetType: 'text',
    size: 450000,
    dateAdded: new Date('2026-05-18T16:50:00Z'),
    tags: ['data', 'feedback', 'raw'],
  },
  {
    id: 'ast-015',
    name: 'readme-instructions',
    assetType: 'text',
    size: 1200,
    dateAdded: new Date('2026-05-22T08:00:00Z'),
    tags: ['documentation', 'internal'],
  },

  // --- 3D (5) ---
  {
    id: 'ast-016',
    name: 'architectural-chair-mesh',
    assetType: '3D',
    size: 85000000,
    dateAdded: new Date('2026-05-28T11:30:00Z'),
    tags: ['3D', 'furniture', 'raw-mesh'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/chair-3D.jpg',
  },
  {
    id: 'ast-017',
    name: 'character-run-animation',
    assetType: '3D',
    size: 142000000,
    dateAdded: new Date('2026-06-01T09:45:00Z'),
    tags: ['3D', 'animation', 'character'],
  },
  {
    id: 'ast-018',
    name: 'scooter-model-textured',
    assetType: '3D',
    size: 23400000,
    dateAdded: new Date('2026-06-03T14:10:00Z'),
    tags: ['3D', 'webgl', 'product'],
    previewUrl: 'https://assets.example.com/previews/scooter.gltf',
  },
  {
    id: 'ast-019',
    name: 'space-helmet-packed',
    assetType: '3D',
    size: 45000000,
    dateAdded: new Date('2026-06-05T16:20:00Z'),
    tags: ['3D', 'game-ready', 'sci-fi'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/helmet.jpg',
    previewUrl: 'https://assets.example.com/previews/helmet.glb',
  },
  {
    id: 'ast-020',
    name: 'sneaker-ar-view',
    assetType: '3D',
    size: 12800000,
    dateAdded: new Date('2026-06-09T10:05:00Z'),
    tags: ['3D', 'ar', 'ios'],
    thumbnailUrl: 'https://assets.example.com/thumbnails/sneaker.jpg',
    previewUrl: 'https://assets.example.com/previews/sneaker.usdz',
  },
];
